apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe-tms
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fe-tms
  template:
    metadata:
      labels:
        app: fe-tms
    spec:
      containers:
        - name: fe-tms
          image: fe-tms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: '1'

---
apiVersion: v1
kind: Service
metadata:
  name: fe-tms-balancer
spec:
  selector:
    app: fe-tms
  ports:
    - protocol: TCP
      port: 8000 # The port to expose to the outside
      targetPort: 8080 # The port the application is running on in the pods
  type: LoadBalancer
  sessionAffinity: ClientIP
